Docs Hab landing page
habitat-sh/habitat pull request #8837
Opened 2023-04-10 21:13 UTC by IanMadd

Two things:

- Update the Hab landing page text at docs.chef.io/habitat/
- moves the menu config from chef-web-docs.

Note that the Netlify build will look a little weird since Netlify defaults to using the menu config in chef-web-docs, which I can't delete until this gets merged.

2023-04-12 21:57 UTC, mwrock requested changes
This largely looks good! In addition to these comments, the preview site has a side menu with a separate `habitat/install` item below `Chef habitat`. It should be a sub menu of Chef Habitat.

2023-04-12 21:57 UTC, mwrock commented on components/docs-chef-io/content/habitat/studio.md
> +- Does Windows suffer from this same issue?
I think you could remove these two lines. They look like they were internal notes.

2023-04-12 21:57 UTC, mwrock commented on components/docs-chef-io/content/habitat/studio.md
>  ### Linux "Docker Studio" aka `rootless_studio`
I would remove `aka rootless_studio` no one uses that term for the docker studio anymore and it may cause confusion.

2023-04-12 23:18 UTC, mwrock commented on components/docs-chef-io/content/habitat/studio.md
> +## Customizing Studio
Not sure when this happened but we used to have docs on customizing the windows studio that seems to have been removed. See the original PR for the docs on that https://github.com/habitat-sh/habitat/pull/7618/files#diff-b4f52172c4e9339a64b98b03edfabe854ab0af5a78ede124794c014655f2fb79L53

2023-04-18 16:31 UTC, IanMadd commented on components/docs-chef-io/content/habitat/_index.md
> +A Habitat Package is an artifact that contains the application codebase, lifecycle hooks, and build dependencies of the application.
Is it more accurate to say, 

> A Habitat Package is an artifact that contains the application codebase, lifecycle hooks, and a manifest that defines build and runtime dependencies of the application.

2023-04-18 18:07 UTC, IanMadd commented
> the preview site has a side menu with a separate habitat/install item below Chef habitat

The preview is generated from the current menu config in chef-web-docs, but not the [menu config that I'm adding in this PR](https://github.com/habitat-sh/habitat/pull/8837/files#diff-698c765916b48947732013f97c108bfdac5877695e10dfff628a8fe5c93781fa). That will get corrected after this content is merged and I can delete Hab menu config in chef-web-docs.

2023-05-16 16:49 UTC, mwrock approved these changes

2023-05-16 16:49 UTC, merged