Initial support: clap-v4 for `pkg-export-container`
habitat-sh/habitat pull request #9306
Opened 2024-07-16 09:06 UTC by agadgil-progress

Using clap-v4 APIs for the `hab-pkg-export-container` binary to mainly demonstrate the usage of clap-v4.

Basic tests pass and basic CLI usage works eg.

```
hab-pkg-export-container core/redis
```

2024-07-17 00:08 UTC, mwrock requested changes
Overall this looks good. Just some minor details in the comments.

2024-07-17 00:08 UTC, mwrock commented on components/pkg-export-container/src/cli.rs
> +            ),
We should be able to remove the "(default: ...)" from the help text since clap outputs that for us.

2024-07-17 00:08 UTC, mwrock commented on components/pkg-export-container/src/cli.rs
> +            .help("Install packages from the specified release channel (default: stable)"),
Should we add a `default_value` for this?

2024-07-17 14:29 UTC, mwrock requested changes
Your changes look good. I have unblocked your build and I am seeing some clippy failures you will need to fix. https://buildkite.com/chef/habitat-sh-habitat-main-verify/builds/12492#0190bff9-9af3-485a-803f-80a8a70fce70

2024-07-18 12:26 UTC, agadgil-progress commented
> Your changes look good. I have unblocked your build and I am seeing some clippy failures you will need to fix. https://buildkite.com/chef/habitat-sh-habitat-main-verify/builds/12492#0190bff9-9af3-485a-803f-80a8a70fce70

@mwrock : Fixed those clippy failures. Take a look.

2024-07-18 12:58 UTC, mwrock approved these changes

2024-07-19 05:51 UTC, merged