Habitat on Apple Darwin
habitat-sh/habitat pull request #9469
Opened 2024-11-12 08:13 UTC by sajjaphani

2025-02-04 15:37 UTC, jasonheath commented
Starting to look at this I feel like the verify pipeline should be updated to run expeditor/scripts/verify/run_studio_test.sh for macOS the same as happens now for both Windows and Linux. Is there something that prevents parity here?

2025-02-12 16:56 UTC, rahulgoel1 commented
@mwrock @agadgil-progress @jasonheath This PR is ready for review i believe. Pls review it this week if possible.

2025-02-13 15:02 UTC, agadgil-progress commented
@rahulgoel1 : The status still shows as `Draft` PR. 

@sajjaphani : Can you squash this PR into a set of few related commits before marking it ready for review?

2025-02-14 06:41 UTC, agadgil-progress commented
@rahulgoel1  / @sajjaphani  : Is there a Jira ticket that describes what exactly is being done in this ticket? Is it CHEF-17583?

2025-02-19 05:03 UTC, agadgil-progress requested changes
I think it's a good idea to rebase this against latest main and squash commits into a few relevant ones otherwise the `git log` will be cluttered with too many trivial commit messages. - the build this was rebased against is kind of old

1. I have mainly reviewed the `plan-build-*` shell scripts. I believe there is a lot of code duplication in `plan-build-linux`, `plan-build-darwin` and `plan-build-darwin-internal` which can be pulled out in a common functionality. May be we want to take that up in a subsequent work but better to mark that as `TODO` in these files at-least.
2. Also the documentation to work with this code exists in a separate repo, unless that is by design - that is if we want to keep all MacOS work *private*, it's a better idea to pull the documentation locally. 
3. Some minor comments/changes otherwise.

This is more like a first pass of review for early feedback. I will continue looking at `components/studio/*` files for further details. I am also trying to work with this code locally and see the mileage. Initial quick tests looked okay.

2025-02-19 13:15 UTC, sajjaphani commented on components/hab/install.sh
> +    b)
We cannot use the same channel to pull the specific hab package, in this case, from the aarch64-darwin-sonoma channel.

2025-02-20 04:32 UTC, agadgil-progress commented
> Starting to look at this I feel like the verify pipeline should be updated to run expeditor/scripts/verify/run_studio_test.sh for macOS the same as happens now for both Windows and Linux. Is there something that prevents parity here? And the follow question is if that does make sense are there other places where the verify pipeline should be updated?

I agree. One challenge that I had while originally reviewing this code is - what is expected to work with this PR from the point of view of supporting MacOS.  Looks like with this PR the studio should work and then there should be a verify pipeline for that - that works (I quickly tested `test/test.sh` which is linux specific as it uses `busybox` and that doesn't work for MacOS). Unless  this PR explicitly calls out what should work and what should not work - it won't be possible to say whether expected functionality is working.

2025-02-21 09:22 UTC, sajjaphani commented
@jasonheath / @agadgil-progress Regarding the tests on macOS, the existing tests will not work. Currently, we do not have a standard set of Habitat packages for macOS in our repository. We will address that in a separate PR. Once those are added, we can start looking into the tests.

2025-02-21 09:28 UTC, sajjaphani commented on components/plan-build/bin/hab-plan-build-linux.sh
> +  case "$pkg_target" in
This check is required until we have a sandbox-based studio for macOS.

2025-02-21 10:51 UTC, agadgil-progress commented
There is a small issue when running with `HAB_STUDIO_BINARY` environment variable set - 

Get the following error - 
```bash
/Users/agadgil/Chef/habitat/components/studio/bin/hab-studio-darwin.sh: line 368: studio_binary_libexec_path: unbound variable
```
This can be fixed by adding following line to function `set_libexec_path()`

```
studio_binary_libexec_path=$libexec_path 
```

Also, trying to build some of the "core" packages is not successful, but this is mainly due to the error `core/clang` not found on the builder (which is not present in the acceptance builder on `unstable` or `aarch64-darwin-sonoma`

```bash 
$ HAB_BLDR_CHANNEL=unstable HAB_BLDR_URL=https://bldr.acceptance.habitat.sh HAB_STUDIO_BACKLINE_PKG=core/hab-backline/1.6.1208 HAB_STUDIO_BINARY=/Users/agadgil/Chef/habitat/components/studio/bin/hab-studio-darwin.sh RUST_LOG=debug sudo -E hab studio build packages/applications/version-management/git/
```

2025-02-21 11:22 UTC, agadgil-progress commented
Trying to build the `core` package locally (as that is a reasonable way of testing the `hab-studio`), faced problems with a few packages, so not following that path `coreutils` build failure with latest `clang` similarly `sed` build failure with latest `clang` (available with `core-packages-internal`)

2025-02-22 04:20 UTC, agadgil-progress commented
> @jasonheath / @agadgil-progress Regarding the tests on macOS, the existing tests will not work. Currently, we do not have a standard set of Habitat packages for macOS in our repository. We will address that in a separate PR. Once those are added, we can start looking into the tests.

Yes - agreed! I believe the correct course of action to be - to first get a working set of core packages and refer to the commits from this branch to build the `core` packages (locally using `hab-auto-build`) and then merge this into master - so that we know the studio from this works. Currently we do not have a good way of making sure the studio from this works. (Tried this with `HAB_STUDIO_BINARY` env variables, but builds fail due to missing core packages.)

Once that is done, build and release packages with the latest code to acceptance (unstable). 

After that we should add test cases using the `CI_BUILDER_CHANNEL` override. 

Finally when everything is ready - make those packages available in `stable`, `base-xxxx` as appropriate. 

Does that make sense?

2025-02-28 05:45 UTC, agadgil-progress commented
I tried to get this working on macOS Sonoma - here is the mileage - 

1. The install script works fine (needs `sudo`)
2. I am trying to build a set of core packages locally (as remote `clang` etc. packages are not available). For that I had to perform few additional installations - `brew install coreutils`, `brew install bash`, `brew install gnu-tar`,  `brew install wget` , `brew install protobuf`, `brew install xz`.  (we need to document this somewhere). 
3. While trying to build `core-packages-internal` locally (because no remote packages are available), I am facing error `clang` not found - while compiling some of the packages, clearly both `clang` and `core/clang` are install and can be invoked, but the `do_build` functions of some of the packages are not able to find it.

2025-02-28 14:06 UTC, sajjaphani commented
> I tried to get this working on macOS Sonoma - here is the mileage -
> 
> 1. The install script works fine (needs `sudo`)
> 2. I am trying to build a set of core packages locally (as remote `clang` etc. packages are not available). For that I had to perform few additional installations - `brew install coreutils`, `brew install bash`, `brew install gnu-tar`,  `brew install wget` , `brew install protobuf`, `brew install xz`.  (we need to document this somewhere).
> 3. While trying to build `core-packages-internal` locally (because no remote packages are available), I am facing error `clang` not found - while compiling some of the packages, clearly both `clang` and `core/clang` are install and can be invoked, but the `do_build` functions of some of the packages are not able to find it.

What do you mean by remote packages not being available? They are present in the acceptance environment. You need to set the URL and channel appropriately to download the remote packages.

The command hab pkg install core/clang --url <BLDR_URL> --channel <CHANNEL> is failing?

The primary purpose of this PR is to bootstrap macOS plans. Are you able to bootstrap the plans?

2025-02-28 15:19 UTC, agadgil-progress commented
> > I tried to get this working on macOS Sonoma - here is the mileage -
> > 
> > 1. The install script works fine (needs `sudo`)
> > 2. I am trying to build a set of core packages locally (as remote `clang` etc. packages are not available). For that I had to perform few additional installations - `brew install coreutils`, `brew install bash`, `brew install gnu-tar`,  `brew install wget` , `brew install protobuf`, `brew install xz`.  (we need to document this somewhere).
> > 3. While trying to build `core-packages-internal` locally (because no remote packages are available), I am facing error `clang` not found - while compiling some of the packages, clearly both `clang` and `core/clang` are install and can be invoked, but the `do_build` functions of some of the packages are not able to find it.
> 
> What do you mean by remote packages not being available? They are present in the acceptance environment. You need to set the URL and channel appropriately to download the remote packages.
> 
> The command hab pkg install core/clang --url <BLDR_URL> --channel is failing?
> 
> The primary purpose of this PR is to bootstrap macOS plans. Are you able to bootstrap the plans?

This is the actual command I ran 

```
$ sudo -E hab-auto-build build -m git 

```
On the `core-packages-internal` and `macOS-plans` branch.  I have modified the `plan.sh` of the `hab-*` plans to point to the latest commit on this branch, so that we know the *local* habitat is built using the latest code.

But build of `perl` and `bzip2` etc. some of the packages fails - because it fails to find the `c compiler`. The `core/clang` package is install (can do `hab pkg exec core/clang clang`). FWIW also installed `brew install gcc` (`gcc` here simply points to `clang`).  

May be I am missing something, but the bootstrap process should not require the remote builder (whatever is required for `install.sh` works fine, because I can use that `hab` binary).

2025-03-03 06:40 UTC, sajjaphani commented
@agadgil-progress  We need a fix for the studio, as it currently requires downloading packages from the builder. This fix involves rebuilding the hab-studio and updating it to the latest commit. You can find the fix here:

https://github.com/habitat-sh/habitat/pull/9469/commits/3dbbe56a58b7c16d719993af23592fefe285be98.

2025-04-03 12:00 UTC, rahulgoel1 commented
@sougata-progress  since the testing is complete are you able to sign off on this PR so that it can be merged?

2025-04-03 19:28 UTC, rahulgoel1 commented
@agadgil-progress  can you pls approve this PR as it has been tested also by @sougata-progress . Once you approve we will merge.

2025-04-08 03:21 UTC, agadgil-progress approved these changes

2025-04-09 12:40 UTC, merged